SUPABASE_URL = "https://rucewsvsynjgaawypcer.supabase.co"
SUPABASE_KEY ="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJ1Y2V3c3ZzeW5qZ2Fhd3lwY2VyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQzMTIyMTEsImV4cCI6MjA5OTg4ODIxMX0.UgGiB5p68HfH-TGnDWjaez90zUGbYHitN4DY62bmvkc"
